services:
  wallet_service:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wallet_service'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'